trigger:
- master
- '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    curl $BEDROCK_BUILD_SCRIPT > build.sh
    chmod +x ./build.sh
  displayName: Download script
  env:
    BEDROCK_BUILD_SCRIPT: https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

- bash: |
    . build.sh --source-only
    init
    get_fab_version
    download_fab
    git_connect
    
    if ! git checkout $BRANCH_NAME; then
      git checkout -b $BRANCH_NAME
    fi
    
    RING_NAME="$SERVICE_NAME-$BRANCH_NAME"
    fab set --subcomponent $SERVICE_NAME.$RING_NAME buildId=$NUMBER

    git add -A
    git config --global user.email "admin@azuredevops.com"
    git config --global user.name "Azure DevOps Bot"
    git commit -m "Fab setting buildId"

    # Remove http(s):// protocol from URL so we can insert PA token
    repo_url=$REPO
    repo_url="${repo_url#http://}"
    repo_url="${repo_url#https://}"

    git push https://$ACCESS_TOKEN@$repo_url
  displayName: Fab set version
  env:
    BRANCH_NAME: $(Build.SourceBranchName)
    ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN)
    REPO: "https://github.com/samiyaakhtar/diamond-rings-cluster"
    NUMBER: $(Build.BuildId)
    SERVICE_NAME: "diamond-rings"