subcomponents:
  diamond-rings-master:
    config:
      author: Samiya Akhtar
      branchName: ""
      buildDate: ""
      buildId: "4454"
      commitId: ""
      image:
        repository: helloringsazure.azurecr.io/diamondrings
        tag: diamond-rings-master-4454
